spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monew
    username: monew
    password: monew1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  data:
    mongodb:
      uri: mongodb://localhost:27017/monew
