spring:
  application:
    name: monew

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: always

  batch:
    jdbc:
      initialize-schema: always  # 개발 환경에서는 'always', 운영 환경에서는 'never'
    job:
      enabled: false  # 애플리케이션 시작 시 모든 배치 작업 자동 실행 방지

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
