spring:
  application:
    name: monew
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}/${MONGO_DB_PROD}?retryWrites=true&w=majority&appName=Cluster0
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: never
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  batch:
    jdbc:
      initialize-schema: never # 배포 안정화 전까지 always
    job:
      name: deleteNotificationJob
      enabled: false
  boot:
    admin:
      client:
        url: http://localhost:9090
logging:
  level:
    root: info
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: warn
  file:
    path: /var/log/monew
    name: ${logging.file.path}/application.log
    archive: ${logging.file.path}/archive
  retention-days: 14

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false


