spring:
  application:
    name: monew
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: always
  batch:
    jdbc:
      initialize-schema: always  # 개발 환경에서는 'always', 운영 환경에서는 'never'
    job:
      name: deleteNotificationJob
      enabled: false  # 애플리케이션 시작 시 모든 배치 작업 자동 실행 방지
  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss
  boot:
    admin:
      client:
        instance:
          name: monew

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
  file:
    path: ./logs
    name: ${logging.file.path}/application.log
    archive: ${logging.file.path}/archive
  retention-days: 7

news:
  naver:
    url: https://openapi.naver.com
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}

aws:
  #  profile-name: monew-acc
  region: ${AWS_REGION:ap-northeast-2}
  credentials:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}

  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
    log-prefix: logs

app:
  db-type: mongodb  # postgresql || mongodb
  version: ${version}
  timezone: Asia/Seoul

server:
  tomcat:
    relaxed-query-chars: '[,]'

springdoc:
  api-docs:
    path: /sb/monew/api/v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
    groups-order: desc

  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers # Actuator 엔드포인트 설정
  endpoint:
    health:
      show-details: "ALWAYS"
  info:
    env:
      enabled: true

info:
  app:
    name: monew
  java:
    version: 17
  spring:
    boot:
      version: 3.4.4
