name: CD - Deploy To ECS

on:
  push:
    branches:
      - release/*
      - release
  pull_request:
    branches:
      - release/*
      - release

permissions:
  contents: read

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY_URI: 462740558166.dkr.ecr.ap-northeast-2.amazonaws.com/team2/monew
  IMAGE_TAG: ${{ github.sha }}
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY2 }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY2 }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant Execution Permission
        run: chmod +x ./gradlew
        working-directory: ./monew

      - name: Build JAR (Skip Test)
        run: ./gradlew clean build -x test
        working-directory: ./monew

      - name: AWS CLI 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: private

      - name: Build And Push
        run: |
          docker build -t $ECR_REPOSITORY_URI:$IMAGE_TAG -t $ECR_REPOSITORY_URI:latest . --platform linux/amd64
          docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
          docker push $ECR_REPOSITORY_URI:latest
